### ISSUE TITLE
Request textDocument/hover failed, and command error

### ISSUE THREAD

**Issue by eniel-rodriguez** [leosj29/jsf-primefaces-intellisense#25]
SO Windows 10 Pro x64
VSCode 1.85.1

```
[Error - 11:18:30 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
```

The command doesn't work either:
![image](https://github.com/leosj29/jsf-primefaces-intellisense/assets/149071591/16bcda04-8294-4ecc-ad6e-62df281619ea)

**Comment by andresfv** [comment]
Greetings Leo, 

Same problem here

SO Windows 10 Pro x64
VSCode 1.85.2

Also
Ubuntu 22.04.2 LTS
VSCode 1.85.2

![error](https://github.com/leosj29/jsf-primefaces-intellisense/assets/3673602/033ee9ad-859f-4b7b-a1b0-463190fda80b)

Output: 
[Error - 14:06:30] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603

**Comment by leosj29** [comment]
Hello, I took on the task of reverting the latest changes made to the extension because I didn't have the time to review them. With this, the extension has returned to its state before the emergence of the problem. At the same time, I want to communicate that I am no longer willing to continue updating the code, so I encourage you to fork the code and develop new features.
 Thank you very much.!!!
